name: Build iOS Tweak (Theos)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  THEOS: $HOME/theos

jobs:
  build:
    runs-on: macos-latest
    name: Build Theos Tweak

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Theos (for faster builds)
        uses: actions/cache@v4
        with:
          path: ${{ env.THEOS }}
          key: theos-${{ runner.os }}-v1

      - name: Install Dependencies
        run: |
          brew install perl ldid dpkg
          echo "export PATH=$THEOS/bin:$PATH" >> $GITHUB_ENV

      - name: Setup Theos and SDKs (skip if cached)
        run: |
          mkdir -p "$THEOS"
          
          if [ ! -d "$THEOS/.git" ]; then
            echo "Cloning Theos..."
            git clone --recursive https://github.com/theos/theos.git "$THEOS"
          fi

          if [ ! -d "$THEOS/sdks" ]; then
            echo "Cloning SDKs..."
            git clone https://github.com/theos/sdks.git "$THEOS/sdks"
          fi
